# Generated by Django 4.2.3 on 2023-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items", models.CharField(max_length=300)),
                ("nom", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("adresse", models.CharField(max_length=200)),
                ("ville", models.CharField(max_length=200)),
                ("pays", models.CharField(max_length=300)),
                ("code", models.CharField(max_length=300)),
                ("date_commande", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_commande"],
            },
        ),
    ]
