# Generated by Django 4.2.3 on 2023-07-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boutique", "0002_commande"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="code",
            new_name="zipcode",
        ),
    ]
